#%RAML 1.0 Trait
usage: Apply this trait to resources/methods for error responses that needs to be returned 
responses:
  400:
    description: Bad request 
    body:
      application/json:
        type: !include ../dataTypes/error-type.raml
        example: !include ../examples/errors/error-response-400.raml
  401:
    description: Unauthorized
    body:
      application/json:
        type: !include ../dataTypes/error-type.raml
        example: !include ../examples/errors/error-response-401.raml      
  404:
    description: Resource not found
    body:
      application/json:
        type: !include ../dataTypes/error-type.raml
        example: !include ../examples/errors/error-response-404.raml
  405:
    description: Method not allowed
    body:
      application/json:
        type: !include ../dataTypes/error-type.raml
        example: !include ../examples/errors/error-response-405.raml
  406:
    description: Not acceptable
    body: 
      application/json:
        type: !include ../dataTypes/error-type.raml
        example: !include ../examples/errors/error-response-406.raml
  415:
    description: Unsupported media type
    body: 
      application/json:
        type: !include ../dataTypes/error-type.raml
        example: !include ../examples/errors/error-response-415.raml
  500:
    description: Internal server error
    body:
      application/json:
        type: !include ../dataTypes/error-type.raml
        example: !include ../examples/errors/error-response-500.raml
  503:
    description: Service Unavailable
    body:
      application/json:
        type: !include ../dataTypes/error-type.raml
        example: !include ../examples/errors/error-response-503.raml
  504:
    description: Gateway Timeout
    body:
      application/json:
        type: !include ../dataTypes/error-type.raml
        example: !include ../examples/errors/error-response-504.raml            