#%RAML 1.0 NamedExample
correlationId: ef99bdd0-85d2-11ed-b109-5c52309a1700
applicationName: mule-application-template
applicationEnvironment: DEV
timestamp: 2022-12-27T11:40:52.946+01:00
infoMessage:
  errorCode: 404
  errorDescription: Resource not found
  errorType: APIKIT:NOT_FOUND