#%RAML 1.0 NamedExample
correlationId: 79662050-fe57-11ee-ad11-02c56ec28031
applicationName: mule-application-template
applicationVersion: v1
applicationEnvironment: DEV
timestamp: 2024-04-19T14:16:54.802Z
infoMessage:
  errorCode: 504
  errorDescription: Service Unavailable
  errorType: Gateway Timeout