{
  "data": {
    "consents": [
      {
        "id": "0ZYbb00000302zPGAA",
        "consentName": "Marketing Email",
        "status": "OptIn",
        "source": "Web",
        "type": "EMAIL"
      },
      {
        "id": "0ZYbb00000302zQGAA",
        "consentName": "Transactional SMS",
        "status": "OptIn",
        "source": "Mobile",
        "type": "SMS"
      }
    ]
  }
}
