#%RAML 1.0 ResourceType

displayName: Readiness probe - Health Check with Dependencies
get:
  displayName: Health Check
  description: Returns the status of the API (including dependencies)
  responses:
    200:
      body:
        application/json:
          type: !include ../dataTypes/readiness-probe-type.raml
          examples: !include ../examples/health-check/readiness-probe-example-response.raml
