#%RAML 1.0 Trait
queryParameters:
  providerNPI:
    type: string
    required: true
    example: "123"
  city:
    type: string
    required: false
    example: "UDR"
  stateCode:
    type: string
    required: false
    example: "MA"
  postalCode:
    type: string
    required: true
    example: "313001"