#%RAML 1.0 Trait
headers:
  Authorization:
    description: |
      Used to send a valid OAuth 2 access token. 
      Format: "Bearer <JWT_TOKEN>"
    type: string
    pattern: ^Bearer .+
    example: Bearer eyJraWQikpYTmhISXNzTnR
