#%RAML 1.0 DataType
type: object
properties:
  firstName:
    type: string
    required: true
  lastName:
    type: string
    required: true
  caregiverFirstName:
    type: string
    required: false
  caregiverLastName:
    type: string
    required: false
  email:
    type: string
    pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
    required: false
  typeOfDiabetes:
    type: string
    required: false
  preferredLanguage:
    type: string
    required: false
  patientDOB:
    type: date-only
    required: false
  relationshipToPatient:
    type: string
    required: false
  leadSource:
    type: string
    required: false
  company:
    type: string
    required: false
  cKey:
    type: string
    required: false
  currentTherapy:
    type: string
    required: false
  genderIdentity:
    type: string
    required: false
  phone:
    type: string
    required: false
  isMobilePhone:
    type: boolean
    required: false
  street:
    type: string
    required: false
  city:
    type: string
    required: false
  stateCode:
    type: string
    required: false
  postalCode:
    type: string
    required: false
  insuranceType:
    type: string
    required: false
  insuranceCompany:
    type: string
    required: false
  sensorCGM:
    type: string
    required: false
  pifProcess:
    type: string
    required: false
  callMe:
    type: string
    required: false
  drupalURL:
    type: string
    required: false
  referralOmnipodSource:
    type: string
    required: false
  consents:
    type: array
    items: !include consent-item-type.raml
    required: false
