#%RAML 1.0 DataType

type: object
description: This is generic common error handling
properties:
  correlationId: 
    type: string
    description: Correlation id used for tracerouting
  applicationName: 
    type: string
    description: Application Name
  applicationEnvironment: 
    type: string
    description: Environment where the application is deployed
  infoMessage:
    type: object
    description: Info Error Message Object 
    properties:
      errorCode:
        type: number
        description: Http error status code
      errorDescription:
        type: string
        description: Error message
      errorType: 
        type: string
        description: Error Type
      