#%RAML 1.0 DataType

type: object
description: Lead response data type after updating a patient lead in Salesforce
properties:
  leadId:
    type: string
    description: Salesforce Lead ID returned from the Composite API response
    required: true
  success:
    type: string
    description: Success flag
    required: false