#%RAML 1.0 DataType 
type: object
properties:
  leadId:
    type: string
    example: 00Qxx0000012345EAA
    required: false
  legacyID:
    type: string
    example: LEG-9876
    required: false
  providerAccountId:
    type: string
    example: 001xx0000032145EAA
    required: false
  practiceAccountId:
    type: string
    example: 001xx0000032146EAA
    required: false
  facilityId:
    type: string
    example: 001xx0000032147EAA
    required: false
  providerLeadId:
    type: string
    example: 00Qxx0000032148EAA
    required: false