#%RAML 1.0 DataType
type: object
description: Request body for creating a provider lead
properties:
  firstName:
    type: string
    description: First name of the provider
    required: true
  lastName:
    type: string
    description: Last name of the provider
    required: true
  city:
    type: string
    description: City
    required: false
  state:
    type: string
    description: State or province name
    required: false
  stateCode:
    type: string
    description: State code
    required: false
  postalCode:
    type: string
    description: Postal code
    required: false  
  patientId:
    type: string
    description: patient identifier from external system
    required: false
  phone:
    type: string
    description: Phone number of the provider
    required: false
  fax:
    type: string
    description: Fax number
    required: false
  leadSource:
    type: string
    description: Source of the lead
    required: false  
  status:
    type: string
    description: Status of the lead
    required: false
  npi:
    type: string
    description: npi of the lead
    required: false
  externalSystemId:
    type: string
    description: externalSystemId of the lead
    required: false
  email:
    type: string
    description: Email
    required: false  
  hcpType:
    type: string
    description: HCP Type
    required: false  
  degreeDescription:
    type: string
    description: Degree Description
    required: false  
  otherDegreeInfo:
    type: string
    description: Other Degree Info
    required: false  
  licenseNumber:
    type: string
    description: License Number
    required: false  
  inquiryDetails:
    type: string
    description: Inquiry Details
    required: false  
  drupalURL:
    type: string
    description: Drupal URL
    required: false  
  statusReason:
    type: string
    description: Status Reason
    required: false  
  practiceName:
    type: string
    description: Practice Name
    required: false  
  facilityId:
    type: string
    description: Facility Id
    required: false  
  providerAccountId:
    type: string
    description: Provider Account Id
    required: false  
  practiceAccountId:
    type: string
    description: Practice Account Id
    required: false      
  street:
    type: string
    description: street
    required: false
  cToken:
    type: string
    description: cToken
    required: false