#%RAML 1.0 DataType
type: object
description: Consent object for provider lead creation request
properties:
  purposeName:
    type: string
    description: Consent purpose name
    required: false
  source:
    type: string
    description: Consent source channel
    required: false
  status:
    type: string
    description: Consent status
    required: false