#%RAML 1.0 DataType

type: object
description: a generic liveliness response
properties:
  name: 
    type: string
    description: The name of the application
  tier: 
    type: string
    description: The tier of the application
  status: 
    type: string
    description: the status of the application
  environment: 
    type: string
    description: the environment of the application
  id: 
    type: string
    description: the trace id of the application
  timestamp: 
    type: datetime
    format: rfc3339
    description: the timestamp of the check
  dependencies:
   type: array
   items:
      type: object
      properties: 
        name: 
          type: string
          description: The name of the dependency
        status: 
          type: string
          description: the status of the dependency
