#%RAML 1.0 DataType
type: object
properties:
  provider:
    type: object
    required: true
    properties:
      firstName:
        type: string
        required: false
      lastName:
        type: string
        required: false
      city:
        type: string
        required: false
      postalCode:
        type: string
        required: false
      state:
        type: string
        required: false
      stateCode:
        type: string
        required: false
      npi:
        type: string
        required: false
      fax:
        type: string
        required: false
      leadSource:
        type: string
        required: false
