## UAT usage — append to VM arguments:
##   -M-Dmule.env=uat -M-Danypoint.platform.gatekeeper=disabled

# Auto Discovery ID (set once registered in Anypoint Platform UAT)
api.id=

# Salesforce — UAT sandbox
sfl.keystore=
sfl.tokenUrl=
sfl.audienceUrl=https://test.salesforce.com
sfl.consumerkey=${azure-key-vault-properties-provider::secret::na-sfl-<project>-consumer-key}
sfl.principal=${azure-key-vault-properties-provider::secret::na-sfl-<project>-principal}
sfl.storepassword=${azure-key-vault-properties-provider::secret::na-sfl-<project>-storepassword}
sfl.certalias=${azure-key-vault-properties-provider::secret::na-sfl-<project>-certalias}

# Salesforce Composite — UAT sandbox
aspn.sfl.keystore=
aspn.sfl.tokenUrl=
aspn.sfl.audienceUrl=https://test.salesforce.com
aspn.sfl.consumerkey=${azure-key-vault-properties-provider::secret::na-sfl-aspn-consumer-key}
aspn.sfl.principal=${azure-key-vault-properties-provider::secret::na-sfl-aspn-principal}
aspn.sfl.storepassword=${azure-key-vault-properties-provider::secret::na-sfl-aspn-storepassword}
aspn.sfl.certalias=${azure-key-vault-properties-provider::secret::na-sfl-aspn-certalias}

# Logger encryption key
logger.encryptionKey=${azure-key-vault-properties-provider::secret::global-logger-encryption-key}
