## QA usage — append below line to VM arguments:
##   -M-Dmule.env=qa -M-Dmule.encryption.key=  -M-Danypoint.platform.gatekeeper=disabled

# Auto Discovery ID
api.id=<replace-with-qa-api-id>

# Logger Encryption Key
logger.encryptionKey=${azure-key-vault-properties-provider::secret::global-logger-encryption-key}

# Salesforce JWT Connection Parameters
sfl.keystore=certs/<replace-with-jks-filename>
sfl.tokenUrl=https://<replace-with-sf-instance>.sandbox.my.salesforce.com/services/oauth2/token
sfl.audienceUrl=https://test.salesforce.com
sfl.consumerkey=${azure-key-vault-properties-provider::secret::<replace-with-consumer-key-secret-name>}
sfl.principal=${azure-key-vault-properties-provider::secret::<replace-with-principal-secret-name>}
sfl.storepassword=${azure-key-vault-properties-provider::secret::<replace-with-storepassword-secret-name>}
sfl.certalias=${azure-key-vault-properties-provider::secret::<replace-with-certalias-secret-name>}

# Anypoint MQ Details
mq.environmentId=<replace-with-qa-environment-id>
mq.queueName=qa-<replace-with-queue-name>
mq.dlq.name=qa-<replace-with-dlq-name>
mq.connectionTimeout=30000
mq.reconnection.frequency=2000
mq.reconnection.attempts=2
mq.app.clientId=${azure-key-vault-properties-provider::secret::<replace-with-mq-client-id-secret-name>}
mq.app.clientSecret=${azure-key-vault-properties-provider::secret::<replace-with-mq-client-secret-secret-name>}

# Notification Util API
notification.api.clientId=${azure-key-vault-properties-provider::secret::<replace-with-notification-client-id-secret-name>}
notification.api.clientSecret=${azure-key-vault-properties-provider::secret::<replace-with-notification-client-secret-secret-name>}
