#%RAML 1.0 DataType
type: object
minProperties: 1
properties:
  source?:
    type: string
    description: The capture source to update on the consent record.
  status?:
    type: string
    description: The privacy consent status to update on the consent record.
