#%RAML 1.0 NamedExample
readiness-probe-example-response.raml:

  {
    "name": "mule-application-template",
    "tier": "Experience",
    "status": "up",
    "environment": "dev",
    "id": "Trans-1234-abc",
    "timestamp": "2023-01-19T09:48:51.67+01:00",
    "dependencies": [
        {
            "name": "cloud",
            "status": "up"
        }
    ]
  }